---
title: "ARMA/ARIMA/SARIMA Models"
---

## ARIMA

### What is ARIMA?

ARIMA(p,d,q) stands for Auto Regressive Integrated Moving Average. It is a class of statistical models for analyzing and forecasting time series data. Specifically, it explains a given time series based on its own past values, that is, its own lags and the lagged forecast errors, so that equation can be used to forecast future values. Any 'non-seasonal' time series that exhibits patterns and is not a random white noise can be modeled with ARIMA models.

The acronym of ARIMA(p,d,q) is descriptive, capturing the key aspects of the model itself. Briefly, they are:

-   AR: Autoregression. A model that uses the dependent relationship between an observation and some number of lagged observations.

-   I: Integrated. The use of differencing of raw observations (e.g. subtracting an observation from an observation at the previous time step) in order to make the time series stationary.

-   MA: Moving Average. A model that uses the dependency between an observation and a residual error. Each of these components are explicitly specified in the model as a parameter.

The basic steps to fit ARIMA models to time series data involve:

-   Plotting the data and possibly transforming the data

-   Determine the stationality of time series and eliminate the stationality if it exist

-   Identifying the dependence orders of the model & Parameter estimation

-   Fit the model

-   Diagnostics & model choice

### Analysis on Stock Price 

This section is going to conduct ARIMA models on UNH, CVS, LLY, AZN and PFE stock prices, and make prediction for next 100 values. Additionally, I run the model on pre-COVID part for UNH data, and made forecasting to cover the COVID-19 time, and compared the real data with the prediction. This aims to see how stock price would act without COVID-19.

Click links below to see the more detailed page.

-   [**UNH**](model_unh.qmd)
-   [**UNH pre-COVID**](model_unh_precovid.qmd)
-   [**CVS**](model_cvs.qmd)
-   [**AZN**](model_azn.qmd)
-   [**LLY**](model_lly.qmd)
-   [**PFE**](model_PFE.qmd)

## SARIMA

The problem with plain ARIMA model is it does not support seasonality. If the time series has defined seasonality, then, go for SARIMA(p,d,q)x(P,D,Q) which uses seasonal differencing. Seasonal differencing is similar to regular differencing, but, instead of subtracting consecutive terms, it subtracts the value from previous season. - [**GDP**](model_gdp.qmd)
